server:
  port: 9915

# API Registry client configuration
eureka:
  instance:
    appname: ${spring.application.name}
    nonSecurePort: ${server.port}
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

spring:
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/health?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: yes
    hibernate:
      ddl-auto: 'update'
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-persistence.xml
  cloud:
    stream:
      jms:
        health:
          enabled: false
        timeout: 5000
  jackson:
    default-property-inclusion: NON_NULL

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
      enabled: false

backbase:
  activemq:
    enable: false


buildingblocks:
  security:
    xss:
      autoconfig: false


# Logging
logging:
  level:
    root: info
    com.sitech.health: info
    sql: info