type: object
required: [ criteriaName , measurement , equivalencePoints , minimumPointsToBeRedeemed , maximumPointsToBeRedeemed ]
properties:
  id:
    type: string
    format: uuid
  bankName:
    type: string
  criteriaName:
    type: string
  measurement:
    type: string
  weight:
    type: string
  equivalencePoints:
    type: string
  minimumPointsToBeRedeemed:
    type: integer
  maximumPointsToBeRedeemed:
    type: integer
  createdAt:
    type: string
    pattern: "yyyy-MM-dd HH:mm:ss"
    description: Creation date
    example: "2022-06-27"
  updatedAt:
    type: string
    pattern: "yyyy-MM-dd HH:mm:ss"
    description: Updated date
    example: "2022-06-27"
  additions:
    $ref: '../lib/schemas/additions.yaml'