openapi: 3.0.3

info:
  title: Health Application API Specification
  description: Specification for Health Application Client API
  version: 1.0.0
  x-icon: credit_card

servers:
  - description: local test
    url: http://localhost:8080/api/v1

tags:
  - name: Retail

paths:
  /client-api/v1/config/redeemConfiguration:
    description: Redeem Configuration
    post:
      security:
        - BearerAuth
      description: Adds or updates a redeem Configuration
      operationId: addRedeemConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/redeem-configuration.yaml'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: 'schemas/redeem-configuration.yaml'
          description: return general status response
        400:
          $ref: 'lib/common-types.yaml#/components/responses/400BadRequest'
        500:
          $ref: 'lib/common-types.yaml#/components/responses/500InternalServerError'
      tags:
        - redeemConfiguration

  /client-api/v1/customerSynchronizeData:
    description: No description available
    post:
      security:
        - BearerAuth
      description: Adds customer fitness Data
      operationId: synchronizeCustomerData
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/fitness-data.yaml'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: 'schemas/fitness-data.yaml'
          description: return general status response
        400:
          $ref: 'lib/common-types.yaml#/components/responses/400BadRequest'
        500:
          $ref: 'lib/common-types.yaml#/components/responses/500InternalServerError'
      tags:
        - customerSynchronizeData

  /client-api/v1/customerLastSynchronizedData:
    get:
      security:
        - BearerAuth
      parameters:
        - in: query
          required: true
          name: deviceId
          schema:
            type: string
            format: uuid
        - in: header
          name: activateDevice
          required: false
          schema:
            type: boolean
      description: No description available
      operationId: getCustomerSynchronizedData
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: 'schemas/health-data.yaml'
          description: if operation is successful
      tags:
        - customerLastSynchronizedData

  /client-api/v1/customerRedeem:
    post:
      security:
        - BearerAuth
      description: Adds or updates a redeem
      operationId: doCustomerRedeem
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/fitness-data.yaml'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: 'schemas/fitness-data.yaml'
          description: return general status response
      tags:
        - customerRedeem

  /client-api/v1/customerSubscription:
    post:
      security:
        - BearerAuth
      parameters:
        - in: header
          name: activateDevice
          required: false
          schema:
            type: boolean
      description: Adds customer Subscription
      operationId: customerSubscribe
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/subscription.yaml'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: 'schemas/subscription.yaml'
          description: return general status response
      tags:
        - customerSubscription
components:
  schemas:
    healthData:
      $ref: 'schemas/health-data.yaml'

