openapi: 3.0.3

info:
  title: Redeem Client API Spec
  description: Specs for Redeem Client API
  version: 1.0.0
  x-icon: credit_card

servers:
  - description: local test
    url: http://localhost:8080/api/v1

tags:
  - name: Retail

paths:
  /client-api/v1/config/redeemConfiguration:
    description: Redeem Configuration
    post:
      security:
        - BearerAuth
      description: Adds or updates a redeem Configuration
      operationId: postRedeemConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/redeem-configuration.yaml'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: 'schemas/redeem-configuration.yaml'
          description: return general status response
        400:
          $ref: 'lib/common-types.yaml#/components/responses/400BadRequest'
        500:
          $ref: 'lib/common-types.yaml#/components/responses/500InternalServerError'
      tags:
        - redeemConfiguration

  /client-api/v1/fitnessData:
    description: No description available
    post:
      security:
        - BearerAuth
      description: Adds or updates a redeem
      operationId: postFitness
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/fitness-data.yaml'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/healthData'
          description: return general status response
        400:
          $ref: 'lib/common-types.yaml#/components/responses/400BadRequest'
        500:
          $ref: 'lib/common-types.yaml#/components/responses/500InternalServerError'
      tags:
        - fitnessData

  /client-api/v1/clientRedeem:
    post:
      security:
        - BearerAuth
      description: Adds or updates a redeem
      operationId: doRedeem
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/fitness-data.yaml'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/healthData'
          description: return general status response
      tags:
        - clientRedeem

  /client-api/v1/clientSubscription:
    post:
      security:
        - BearerAuth
      description: Adds or updates a subscribe
      operationId: subscribe
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/subscription.yaml'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: 'schemas/subscription.yaml'
          description: return general status response
      tags:
        - subscription

  /client-api/v1/activateDevice:
    post:
      security:
        - BearerAuth
      description: Activate Device
      operationId: activateDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'schemas/deviceActivation.yaml'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: 'schemas/deviceActivation.yaml'
          description: return general status response
      tags:
        - deviceActivation

components:
  schemas:
    healthData:
      type: object
      properties:
        fitnnessData:
          $ref: 'schemas/fitness-data.yaml'
        redeemConfiguration:
          $ref: 'schemas/redeem-configuration.yaml'
        additions:
          $ref: '../lib/schemas/additions.yaml'
