type: object
required: [ bankId , factor , pointTarget , minimumPointsToBeRedeemed , maximumPointsToBeRedeemed ]
properties:
  bankId:
    type: string
  bankName:
    type: string
  factor:
    type: string
  pointTarget:
    type: integer
  minimumPointsToBeRedeemed:
    type: integer
  maximumPointsToBeRedeemed:
    type: integer
  pushInterval:
    type: integer
    description: Push interval in second